# Force Redeploy 2026-04-17git add .
name: Deploy to Xserver
on:
  repository_dispatch:
    types: [main]
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # ここを20から22に変更しました

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}

      - name: Deploy to Xserver via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # Astroの場合、./out/ ではなく ./dist/ です
          server-dir: /aircon-osaka.jp/public_html/